name: Java CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.3

      - run: ls -la
      - run: cd app
      - run: ls -la
